### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by exocode** [kentaroi/sshkit-sudo#10]
my task looks like this:
```
  desc 'initialize certbot / letsencrypt for cloudflare'
  task :init do
    on roles(:app), in: :sequence do
      execute! :sudo, :touch, '/etc/letsencrypt/cloudflare.ini'
      execute! :sudo, :chmod, '600 /etc/letsencrypt/cloudflare.ini'
      # also tried execute! :sudo, :printf,..... 
      sudo :printf, "'dns_cloudflare_email = my@email.com\ndns_cloudflare_api_key = #{fetch(:cloudflare_api_key)}' > /etc/letsencrypt/cloudflare.ini"
    end
  end
```

Creating files works, but as I try to write into it, it stops.
Also tried printf without touching first
But I always get this error:

```

 04 sudo printf 'dns_cloudflare_email = my@email.com
dns_cloudflare_api_key = 123456789890…
      04 bash: /etc/letsencrypt/cloudflare.ini: Permission denied
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@139.162.128.205: sudo exit status: 1
sudo stdout: bash: /etc/letsencrypt/cloudflare.ini: Permission denied
sudo stderr: Nothing written
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
SSHKit::Command::Failed: sudo exit status: 1
sudo stdout: bash: /etc/letsencrypt/cloudflare.ini: Permission denied
sudo stderr: Nothing written
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.14.0/lib/sshkit/command.rb:99:in `exit_status='
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-sudo-0.1.0/lib/sshkit/sudo/backends/netssh.rb:50:in `execute_command!'
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-sudo-0.1.0/lib/sshkit/sudo/backends/abstract.rb:21:in `block in create_command_and_execute!'
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-sudo-0.1.0/lib/sshkit/sudo/backends/abstract.rb:21:in `tap'
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-sudo-0.1.0/lib/sshkit/sudo/backends/abstract.rb:21:in `create_command_and_execute!'
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-sudo-0.1.0/lib/sshkit/sudo/backends/abstract.rb:12:in `execute!'
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-sudo-0.1.0/lib/sshkit/sudo/backends/abstract.rb:6:in `sudo'
config/deploy.rb:105:in `block (3 levels) in <top (required)>'
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.14.0/lib/sshkit/backends/abstract.rb:29:in `instance_exec'
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.14.0/lib/sshkit/backends/abstract.rb:29:in `run'
/Users/jan/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => letsencrypt:init
```

Did I miss something?

**Comment by exocode** [comment]
the file permissions look like this:

    #/etc/letsencrypt:
    -rw-------  1 root root    0 Sep  5 11:41 cloudflare.ini

**Comment by exocode** [comment]
Got it working by:

      execute! :sudo, "echo 'dns_cloudflare_email=my@email.com\ndns_cloudflare_api_key=#{fetch(:cloudflare_api_key)}' | sudo tee /etc/letsencrypt/cloudflare.ini"
